### ISSUE TITLE
Makefile4CubeMX on Raspbian

### ISSUE THREAD

**Issue by oleksandr314** [duro80/Makefile4CubeMX#1]
Hi
I have recently installed STM32CubeMX and all necessary packages for developing on STM32  (gcc-arm-none-eabi, binutils-arm-none-eabi, libnewlib-arm-none-eabi, codeblocks, stlink) 
But I have some issues with CubeMX2Makefile. After opening directory where CubeMX project was generated I typed in terminal

pi@raspberrypi:~/pr/pr1 $ CubeMX2Makefile.py .
bash: CubeMX2Makefile.py: command not found

Any idea?

**Comment by duro80** [comment]
Hello  oleksandr314.
try this: 
- install the script by: sudo ./install
- open terminal in directory, where SW4STM32 project was generated
- type: CubeMX2Makefile.py .
Or without installing:
- open terminal in directory, where SW4STM32 project was generated
- type: /your/path/to/script/CubeMX2Makefile.py .

**Comment by oleksandr314** [comment]
The same thing 
pi@raspberrypi:~ $ sudo ./install
sudo: ./install: command not found

**Comment by duro80** [comment]
Hello.
Are you in directory with Makefile4CubeMX files? You must be in directory where install script is located.
Send me output of "cd" command, from where you run the ./install script.

**Comment by oleksandr314** [comment]
Hi. The output is following:

pi@raspberrypi:~/Makefile4CubeMX $ sudo ./install
ln: failed to create symbolic link ‘/usr/bin/CubeMX2Makefile.py’: File exists

**Comment by duro80** [comment]
Script Makefile4CubeMX.py was installed, but installation script wrong detect previously installed file.
Now I can try to use Makefile4CubeMX.py as is in my first comment.

So, I make a change in instalation script. You can pull this repo (git pull).

**Comment by oleksandr314** [comment]
All works good. Thank You.

But I noticed some mismatch. In article
(https://startingelectronics.org/tutorials/STM32-microcontrollers/programming-STM32-flash-in-Linux/)
and  generated file "Makefile" are different paths to file "st-flash"
/ usr / bin
/ usr / local / bin
respectively.

And another problem  after changing the code. 
In order to fill it in the controller you need to press the button "reset" on developer board. Do you know how to fix it?

**Comment by duro80** [comment]
Hello.
In current version of stlink, the binaries are located in /usr/local/bin.
Second question is about stlink project. Download latest version of stlink (https://github.com/texane/stlink), it may solve you problem.
